version: "3.8"

services:

  backend:
    build: ./chatbot-builder-backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - FRONTEND_URL=http://localhost
    volumes:
      - ./chatbot-builder-backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./chatbot-builder-frontend
    container_name: chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped